name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
  todolist_cicd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: install dependency injection
        run: |
          cd todolist
          npm install

      - name: build/run
        working-directory: todolist
        run: |
          npm run build
          npm run serve   
