name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
  todolist_cicd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: check2
        run: |
          whoami
          cd todolist
          pwd
          ls
