name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
  todolist_cicd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: deploy 
        working-directory: todolist
        run: |
          npm install
          npm run build
          npm run serve

