name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
  todolist_cicd:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: todolist

    steps:
      - uses: actions/checkout@v2

      - name: install dependency injection
        run: npm install

      - name: build/run
        run: |
          npm run build
          npm run serve   
